name: release-macos-intel

on:
  push:
    tags:
      - "v*"
  release:
    types: [created, published]
  workflow_dispatch:
    inputs:
      tag:
        description: "v0.1.0"
        required: false
        default: "dev"

jobs:
  build-and-release:
    name: Build macOS (Intel) and Release
    runs-on: macos-12
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (release)
        run: cargo build --release

      - name: Prepare artifacts
        env:
          INPUT_TAG: ${{ github.event.inputs.tag }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          set -euxo pipefail
          APP_NAME=stock-cli
          # Determine tag name across different triggers
          TAG_NAME="${GITHUB_REF_NAME}"
          if [ -z "${TAG_NAME}" ] || [ "${TAG_NAME}" = "" ]; then
            TAG_NAME="${RELEASE_TAG:-${INPUT_TAG:-dev}}"
          fi
          DIST_DIR=dist
          mkdir -p "$DIST_DIR"
          PKG_NAME="${APP_NAME}-macos-x86_64-${TAG_NAME}"
          # Package binary + required files
          cp target/release/${APP_NAME} ${APP_NAME}
          tar -czf "${DIST_DIR}/${PKG_NAME}.tar.gz" ${APP_NAME} config.json stock_code.csv README.md || {
            echo "Ensure config.json and stock_code.csv exist at repo root."; exit 1;
          }
          shasum -a 256 "${DIST_DIR}/${PKG_NAME}.tar.gz" > "${DIST_DIR}/${PKG_NAME}.tar.gz.sha256"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.sha256
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
